project:
  type: manuscript
  output-dir: _manuscript
  execute-dir: project

manuscript: 
  article: index.qmd
  notebooks: 
    - notebook: notebooks/baseline-summary.qmd
    - notebook: notebooks/outcomes.qmd

format:
  html:
    theme: journal
    fontsize: 1em
    html-table-processing: none
    cap-location: margin
    toc-expand: true
    grid:
      body-width: 800px
      sidebar-width: 250px
      margin-width: 200px

format-links:
  - pdf

execute: 
  freeze: false
  warning: false
  message: false
