project:
  type: default
  output-dir: _reports
  execute-dir: project

format:
  pdf:
    documentclass: scrartcl
    geometry:
      - inner=1cm
      - outer=1cm
      - left=3cm
      - right=3cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    pdf-engine: lualatex
    papersize: a4
    fontsize: 10pt
    mainfont: TeX Gyre Pagella
    mainfontoptions:
      - Numbers=Proportional 
      - Ligatures=TeX
    sansfont: Linux Biolinum O
    sansfontoptions: 
      - Ligatures=TeX
      - Numbers=Proportional
    mathfont: TeX Gyre Pagella Math
    linestretch: 1.25
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    number-sections: true
    colorlinks: true
    link-citations: true
    tbl-pos: "H"
    fig-dpi: 150
    template-partials: 
      - tex/toc.tex
    include-in-header:
      text: |
        \usepackage[font=small,labelfont={bf,small},listformat=simple]{caption}
        \usepackage{makecell}
        \usepackage{moresize}
        \setkomafont{section}{\fontsize{14}{14}\selectfont}
        \usepackage{geometry}

execute: 
  freeze: false
  warning: false
  message: false
  echo: false

knitr:
  opts_chunk: 
    dev: cairo_pdf
