project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - "*.qmd"
    - "!reports/"


website:
  title: "OPTIMUM Trial Data"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:notebooks

  sidebar:
    - id: notebooks
      title: Notebooks
      style: "docked"
      contents:
        notebooks

format:
  html:
    theme: journal
    page-layout: article
    fontsize: 1em
    html-table-processing: none
    cap-location: margin
    toc: true
    toc-expand: true
    grid:
      body-width: 1000px
      sidebar-width: 300px
      margin-width: 300px

execute: 
  freeze: false
  warning: false
  message: false
