default:
  raw_data_stage1_path: "data/raw/stage1"
  raw_data_stage2_path: "data/raw/stage2"
  raw_data_stage2_file: "redcap-labelled-2025-09-08.qs"
  combined_data_file: "data/derived/optimum-data.qs"
