---
title: |
  Efficacy of an early first dose of whole-cell pertussis vaccine in infants for the prevention of IgE-mediated food allergy: A randomised controlled trial
author:
  - name: Gladymer Pérez Chacón
    email: xxx
  - name: James Totterdell
    email: james.totterdell@sydney.edu.au
    affiliations:
      - id: usyd
        name: The University of Sydney
  - name: Tom Snelling
    email:
    attributes:
        corresponding: true
date: last-modified
bibliography: references.bib

format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal of Allergy and Clinical Immunology
      formatting: preprint
      model: 3p
      layout: twocolumn
      cite-style: number

keywords:
  - Diphtheria-Tetanus-Pertussis Vaccine
  - Diphtheria-Tetanus-acellular Pertussis Vaccines
  - Food Hypersensitivity
  - Infant
  - Australia

abstract: |
  # Background {.unnumbered}

  Timely introduction of peanut, egg, and cow's milk into the infant's diet reduces the risk of developing IgE-mediated food allergies to these foods. Additional strategies to promote oral tolerance and prevent food allergic reactions are being investigated in clinical trials.

  # Objective {.unnumbered}

  We aimed to determine if a dose of whole-cell pertussis vaccine (wP) at 6 weeks old, in lieu of acellular pertussis (aP) vaccine, could reduce the incidence of IgE-mediated food allergy in infants.

  # Methods {.unnumbered}

  In this multicentre, randomised, observer-blinded, parallel, two-stage, Bayesian adaptive trial we assigned Australian infants to one of two pertussis vaccination schedules. These consisted of either a first dose of a WHO-prequalified wP combination vaccine (Pentabio®, PT Bio Farma Indonesia) at approximately six weeks old, followed by aP combination vaccine at ages four, six, and 18 months ("mixed wP/aP" schedule), or the standard homologous aP prime boost at the same ages ("aP-only" schedule). The primary outcome was IgE-mediated food allergy with evidence of food sensitisation by age 18-months, confirmed where necessary by medically supervised oral food challenge(s).

  # Results {.unnumbered}

  # Conclusions {.unnumbered}

  There is little evidence of a clinically meaningful reduction in IgE-mediated food allergy in infants receiving a mixed wP/aP versus the standard aP-only schedule. Funded by the National Health and Medical Research Council of Australia; ANZCTR number, ACTRN12616000215426.

  # Clinical Implications {.unnumbered}

  An early first dose of wP is unlikely to meaningfully reduce the probability of developing IgE-mediated food allergy, eczema, or atopic sensitisation in infants and toddlers.
---

# Introduction

IgE-mediated food allergy affects approximately 10\% of Australian infants and is a leading cause of paediatric anaphylaxis presentations [@osborne2011; @mullins2022]. Despite national guidelines promoting early infant feeding since 2016, the population-level impact of early dietary introduction of peanut and egg has been smaller than expected given the effects observed in landmark clinical trials, with evidence of heterogeneity according to parental region of birth and early-onset eczema [@odoi2026; @soriano2022; @koplin2026]. Therefore, preventive strategies beyond dietary modification remain a priority.

The whole-cell pertussis (wP) vaccine is an essential component of the global Expanded Program of Immunisation. Recognised for its high protective efficacy against severe pertussis disease, wP vaccines have been administered to at least 1.4 billion children in Gavi-supported countries since 2000 [@simondon1997; @sheridan2012; @klein2013; @dtp-cont]. In Australia, a locally manufactured wP-based combination vaccine was withdrawn from the National Immunisation Program (NIP) and replaced with a subunit acellular pertussis (aP) combination vaccine between 1997 and 1999 @mcintyre1998. A case-control study suggested that Australian children born during the transition to aP vaccines who developed IgE-mediated food allergy were less likely to have received wP, rather than aP, as their first pertussis vaccine dose in infancy (odds ratio 0.77; 95% confidence interval, 0.62--0.95) @estcourt2020.

Compared to aP vaccines, wP vaccines are more reactogenic and induce a lifelong Th~1~ and Th~17~ polarised immuno-phenotype. This effect may be driven by the adjuvant properties of lipopolysaccharide within the whole-killed *Bordetella pertussis* cells [@patterson2018; @dasilvaantunes2018; @iwasaki2020]. Compared to priming with aP vaccines, there is evidence that priming with wP vaccines attenuates Th\textsubscript{2}-mediated humoral immunity against diphtheria (DT) and pertussis toxins (PT) [@aalberse2019; @nilsson1998; @dasilvaantunes2021]. However, unlike previous reports, we found no evidence of an effect on tetanus toxoid (TT) IgE responses [@perez2024immunogenicity; @mascart2007; @holt2016].

Given the association observed in the case-control study and biological plausibility, we hypothesised that an early first dose of wP could help induce a balanced Th~1~/Th~17~/Th~2~ immunonophenotype in young infants with atopic predisposition, and thereby help to prevent the development of food sensitisation and IgE-mediated food allergy. The OPTIMUM (Optimising Immunisations Using Mixed Schedules) study was therefore designed to evaluate whether substituting the first aP vaccine dose with a wP vaccine would prevent IgE-mediated food allergy, compared to the standard aP-only vaccine schedule.

# Methods

## Trial design and participants
 
OPTIMUM was an observer and participant-blinded, two-stage, Bayesian group-sequential randomised trial, conducted at four active study sites across the states of Western Australia (Perth Children's Hospital), Victoria (Murdoch Children's Research Institute), and New South Wales (Sydney Children's Hospital, Randwick and The Children's Hospital at Westmead), and a non-enrolling site (Fiona Stanley Hospital, Perth, Western Australia) [@pérezchacón2020; @totterdell2022].

Healthy infants born from 32 weeks gestation were randomised 1:1 to receive either a heterologous pertussis priming schedule consisting of a first dose of a WHO-prequalified 5-in-1 wP combination vaccine at approximately six weeks old (DTwP-Hib-HepB; Pentabio® PT Bio Farma, Indonesia; 0.5 mL) @rusmil2015, followed by a 6-in-1 aP combination vaccine (DTaP-Hib-HepB-IPV; Infanrix hexa®, GSK; 0.5 mL) at four and six months old ("mixed wP/aP schedule"), or standard 3-dose homologous pertussis priming with the 6-in-1 aP combination vaccine at the same ages ("aP-only schedule"). To ensure each child received at least three primary doses of polio vaccine (IPV) while maintaining blinding, DTaP-IPV (Infanrix IPV, GSK; 0.5 mL intramuscular) was administered to all infants at 18 months old in lieu of the Australian standard  DTaP. Infants with planned travel to Afghanistan, Pakistan, or any other polio affected region (according to the Global Polio Eradication Initiative) at any time before completion of the study were deemed ineligible at enrolment @eradicat. The wP combination vaccine (either single dose or multidose vials, Pentabio®, PT Bio Farma, Indonesia) was purchased directly from its manufacturer for the implementation of this trial; all other vaccines were sourced from Australia's National Immunisation Program.

Stage one involved the first 150 infants enrolled at Perth Children's Hospital only. It was designed to compare IgE-mediated immune responses to TT post-priming and boosting in each group. We solicited adverse event data following each pertussis vaccine dose, and assessed the non-inferiority of the IgG responses to DTP and co-administered non-DTP vaccine antigens in the mixed wP/aP schedule versus the aP-only study arms. Those data have been reported previously [@perez2024immunogenicity; @pérezchacón2025]. Stage two involved all four study sites, with more streamlined follow-up and a single phlebotomy scheduled only for the first 150 infants enrolled at Perth Children's Hospital. In this subset of infants, we solicited adverse event data following the first pertussis vaccine dose at age 6 weeks and the first booster dose at age 18 months.

## Trial procedures

The study protocol and statistical analysis plan have been published elsewhere [@pérezchacón2020; @totterdell2022]. Briefly, participants were enrolled between age six and <12 weeks, and randomised with equal probability to the mixed wP/aP schedule versus the aP-only schedule, using the allocation sequence generated by the trial statistician through computer block randomisation with block sizes of six, eight, and 10 stratified by study site and concealed in opaque envelopes. The six-week pertussis containing vaccine was administered intramuscularly by an unblinded research nurse who had no further involvement in study visits or trial procedures. A 15 mg/Kg dose of oral paracetamol was given before the six-week vaccines; parents were recommended to administer two further paracetamol doses six hours apart, but this was not observed. Routine NIP vaccines were co-administered @australiangovernmentdepartmentofhealth2025.

At the discretion of each study site, infants enrolled in stage two had a baseline SCORAD (SCORing Atopic Dermatitis) or alternative clinical reporting methods to measure the extent and severity of skin inflammation. Parents received a printed copy of the 2016 Australasian Society of Clinical Immunology and Allergy (ASCIA) Infant Feeding and Allergy guidelines and were encouraged to follow these recommendations. These guidelines recommend the introduction of solids, including peanuts and hen's egg, once the infant is developmentally ready; this is generally at around six months old and not before four months old. They also recommend complementary feeding with other common food allergens by 12 months old, with emphasis on foods regularly consumed by the family [@netting2017; @vale2026]. The age (stage one) or date (stage two) of introduction of potentially allergenic solid foods was reported at each scheduled study visit and via phone or electronic contact.

A skin prick test (SPT) was scheduled for all infants between age 12 months and 18 months. Protocolised allergens were cow's milk, hen egg, peanut, house dust mite (*Dermatophagoides pteronyssinus*), cat, and rye grass (*Lolium perenne*). At the discretion of the site principal investigator, additional unscheduled skin prick tests were also performed as part of the routine assessment of infants with suspected IgE-mediated food reactions.

Participants with evidence of sensitisation on SPT to the food of interest and either of (1) a history of clinician-confirmed food anaphylaxis, (2) a history of food allergic reaction (consistent with PRACTALL criteria) @sampson2012, (3) no history, or an equivocal history of anaphylaxis to that specific food; as well as (4) those with a negative SPT for a specific food but with a history suggestive of IgE-mediated allergy to that specific food were invited to undergo an oral food challenge (OFC) subject to the clinical judgment of the allergist lead at each study site. OFCs followed each site-specific procedure and were scored by an investigator blinded to vaccine allocation using the PRACTALL scoring system @sampson2012.

Safety monitoring, data collection, case definition and reporting of adverse events (AEs) followed national guidelines @guidance2016. In stage one, we captured unsolicited AEs occurring within seven days of pertussis vaccine doses scheduled at six weeks, four months, six months and 18 months; in stage two we captured unsolicited AEs at six weeks and at 18 months old for the first 150 study participants enrolled in stage two at Perth Children's Hospital only.

Adverse events of special interest (AESIs) including pertussis infection and hypotonic hyporesponsive episodes were collected throughout the study @pérezchacón2020. All serious adverse events (SAEs) occurring from enrolment to six months post-randomisation were captured; any events deemed related to either study vaccines or study procedures were captured throughout the study period. All AEs were coded according to the Medical Dictionary for Regulatory Activities (MedDRA) System Organ Class categorisation and were reviewed quarterly by an independent Data and Safety Monitoring Committee (DSMC).

## Trial outcomes

The primary outcome was IgE-mediated food allergy with evidence of food sensitisation on SPT by age 12 to <19 months and confirmed (where necessary) by a medically supervised OFC. The primary outcome was met if there was either unequivocal evidence of IgE-mediated food allergy, or if IgE-mediated food allergy was deemed highly likely by the  site allergist who was blinded to group allocation. Evidence of IgE-mediated food allergy was deemed unequivocal if there was either: (1.a) a positive OFC with evidence of sensitisation on SPT to the food of interest, or (1.b) a history of clinician-diagnosed food anaphylaxis (symptoms affecting at least two of the following: skin, gastrointestinal tract, respiratory tract, cardiovascular system), with evidence of sensitisation on SPT to the food of interest. IgE-mediated food allergy was deemed highly likely if there was (2) a history of food allergic reaction consistent with PRACTALL criteria, with evidence of sensitisation on SPT to the food of interest @sampson2012. 

Additional clinical and mechanistic outcomes were new-onset parent-reported clinician-diagnosed  eczema by (1) six months or (2) 12 months old and a positive SPT to any allergen by approximately 12 months old (onset defined by the documented age at first occurrence), and (3) an SPT more than 1 mm or (4) more than 3 mm greater than the negative control to at least one allergen by approximately 12 months old (12 to <19 months).

Stage one six- and seven-month old immunogenicity and reactogenicity data have been reported previously @perez2024immunogenicity; pre- and post-booster responses to the 18-month dose of DTaP-IPV will be reported separately.

## Trial oversight

Approval was obtained from the Child and Adolescent Health Service Human Research Ethics Committee and **XXX**. Written informed consent was obtained from one parent or guardian of each infant enrolled in this trial. An independent DSMC provided safety oversight.

The trial was registered with the Australian New Zealand Clinical Trial Registry (ACTRN12616000215426) and funded by the National Health and Medical Research Council (NHMRC GNT1158722) and the Western Australia Health Research Fund. The funders had no involvement in the study design, data collection, data analysis, data interpretation, or writing of the report.

## Statistical Analysis

This trial used an adaptive group sequential design and Bayesian inference as detailed the protocol and the statistical analysis plan @totterdell2022.  In brief, we hypothesised that assignment to the mixed wP/aP schedule would be superior to the standard aP-only schedule with respect to the incidence of IgE-mediated food allergy by 12 to <19 months.

The primary analysis used independent beta-binomial models to estimate the difference in probability of IgE-mediated food allergy between the two vaccine strategies; uniform priors were assumed for both response probabilities. Secondary analyses assumed a logistic regression model for occurrence of IgE-mediated food allergy adjusting for study site, sex, breastfeeding status, birth order, parental income, mode of delivery, and family history of atopic disease at baseline. The analyses of clinical and mechanistic secondary outcomes followed the same approach. For all summaries and analyses, all participants were included and grouped according to their randomly assigned study intervention (ITT).

A posterior probability for reduction in IgE-mediated food allergy of at least 0.95 was considered evidence of superiority. A first interim analysis was scheduled to occur after the 200th participant completed the study. Additional interim analyses were to occur for every additional 200 participants unless a stopping rule was met or the maximum sample size had been reached. At each analysis, the trial could be stopped for expected success or futility if the predicted probability of meeting the superiority condition was greater than 0.95 or less than 0.05 respectively based on the posterior predictive distribution from the primary analysis model @totterdell2022.

A maximum sample size of 3,000 infants was selected with 1:1 randomisation. The thresholds above were selected based upon trial simulations used to estimate their effect on trial operating characteristics under various enrolment rates, in particular type I and type II error rates and expected stopping times were assessed. Assuming 10% incidence of IgE-mediated food allergy by age 12 months in the aP-only schedule group simulations indicated the trial would have 85% power for detecting a reduction to 7% in the mixed wP/aP schedule group under the specified thresholds. Before any efficacy analyses were conducted, the maximum sample size was revised to 2,000 participants (1,000 per arm) due to feasibility constraints. Statistical power was reassessed using the same thresholds where the design had 80% power for a reduction from 10.0% to 6.6%.

## Early trial termination

Enrolment commenced at Perth Children's Hospital and stage one was completed on **XXX**. However, while stage two was in progress, we became unable to procure further doses of the wP combination vaccine approved for this study (Pentabio® PT Bio Farma, Indonesia) or any alternative WHO-prequalified wP-based formulations. Following consultation with the DSMC, the trial steering committee, and the Human Research Ethics Committee,  enrolment was terminated upon enrolment of 972 infants (49% of the planned maximum sample size) and after one interim analysis in which no stopping rule had been met.

# Results

## Participants

From March 2018 to December 2023, a total of 975 infants were assessed in clinic for eligibility and 972 were randomised **(Figure 1)**. Except for one infant, all correctly received either aP or wP as assigned for their first dose.

Overall, 463 (48%) of 972 infants were female, 924 (95%) were born to a mother receiving dTaP in the preceding pregnancy, and 833 (86\%) had a family history of atopy in at least one first-degree relative. Baseline characteristics were similar across the study groups **(Table 1)**. Timing of introducing solid foods up to 18-months of age were similar across the study groups **(Supplement)**.

## IgE-mediated food allergy

The primary endpoint of unequivocal or highly likely IgE-mediated food allergy was met in 26 of 486 (5.3%) in the aP-only group and 31 of 486 (6.4%) in the mixed wP/aP group **(Table 2)**. The estimated difference in IgE-mediated food allergy between recipients of the mixed wP/aP schedule versus the aP-only schedule was 0.01 (-0.02, 0.04) [posterior median (95\% credible interval)]. The probability of a reduction in IgE-mediated food allergy under the mixed wP/aP compared to aP-only schedule was 0.25. Results from the secondary (adjusted) analyses were nearly identical to the primary analysis **(Supplement)**.

We calculated the predicted probability of superiority using the data from the 972 participants enrolled. The estimated predicted probability of superiority assuming the trial enrolled to the maximum of 2,000 participants was estimated to be <0.01 which would have met the pre-specified trial futility criteria.

## New-onset eczema

## Skin prick test sensitisation

## Safety

# Discussion

# Acknowledgements

The authors wish to dedicate this work to the memory of Professor Katrina (Katie) Allen AO, who passed away peacefully in January 2026. We express our gratitude for her outstanding contributions to the field of paediatric allergy and to the development of the OPTIMUM study National Health and Medical Research Council grant proposal.


# References
