# Summary

The overall objectives of this study were to determine if, compared to the existing pertussis vaccine schedule of three priming doses of acellular pertussis (aP) vaccine, a single dose of whole-cell pertussis (wP) vaccine at approximately 2 months of age, followed by two doses of aP vaccine at approximately 4 and 6 months of age:

1. Protects against the development of clinical IgE-mediated food allergy.
2. Protects against the development of an atopic immunophenotype, as evidenced by a reduction in the proportion of titres above the assay limit of detection or a reduction in the mean fold-rise in the log titres of total IgE, anti-tetanus toxoid (TT) IgE, and food-associated IgE in response to the third pertussis-containing vaccine at approximately age 6 months (stage 1).
3. Is associated with a protective pertussis antibody response, as evidenced by no reduction in the proportion of children who have at least a 4-fold rise in anti-pertussis toxin (PT) IgG antibody responses and no reduction in the mean fold-rise in PT-IgG, to a fourth pertussis-containing vaccine at approximately age 18 months (stage 1 and stage 2, Perth Children’s Hospital (PCH)/The Kids Research Institute Australia[^1] study site.)
4. Is associated with an acceptable reactogenicity profile (stage 1 and stage 2, PCH/The Kids Research Institute Australia study site).

*__1.__ (@sec-clinical-mechanistic-outcomes) There was little evidence of a substantial benefit of wP compared to aP at 2 months of age on protection against the development of clinical IgE-mediated food allergy. For the primary outcome, the estimated difference [posterior median (95% CrI)] in IgE-mediated food allergy risk for wP compared to aP was 0.01 (-0.02, 0.04), that is anywhere from a 2%pt. reduction to a 4%pt. increase were plausible differences given the data.*

*For the secondary outcome of new-onset eczema by 6 and 12 months of age the estimated difference in risk for wP compared to aP was -0.01 (-0.04, 0.02) and -0.01 (-0.04, 0.03) respectively. For the secondary outcome of skin prick test positivity at >1mm and ≥3mm relative to negative control the estimated difference in risk for wP compared to aP was 0.01 (-0.04, 0.06) and 0.01 (-0.04, 0.05) respectively, both showing little evidence of reduction under the wP schedule compared to aP.*

*__2.__ (@sec-ige) For total IgE the estimated [posterior median (95% CrI)] geometric mean ratio for wP compared to aP at 6-months was 0.99 (0.64, 1.51) and at 7-months was 0.92 (0.61, 1.40) equating to a geometric mean fold-rise ratio of 0.94 (0.72, 1.22). These estimates were imprecise, but show little evidence of a reduction in geometric mean concentrations.* 

*For TT-IgE, geometric mean ratios could not be estimated precisely given a low number of detectable concentrations. Similarly for egg white IgE and whole egg IgE with 6-month geometric mean ratios estimated as 0.49 (0.07, 2.98) and 0.98 (0.21, 4.28) respectively, and 7-month ratios as 0.65 (0.16, 2.46) and 0.73 (0.17, 2.94) respectively.*

*The proportion of concentrations above detection limits were similar between the groups with the largest estimated reduction being in egg white IgE with an estimated difference in quantitation of -0.09 (-0.23, 0.04) at 6-months and -0.10 (-0.26, 0.05) at 7-months of age.*

*__3.__ (@sec-igg) The estimated geometric mean ratio [posterior median (95% CrI)] for PT IgG at 18-months and 19-months of age were 1.19 (0.94, 1.51) and 1.69 (1.33, 2.14) respectively, indicating no meaningful reduction in IgG, and a probable increase. The corresponding geometric mean fold-rise ratio was 1.42 (1.09, 1.84).*

*There was no reduction in the probability of a 4-fold rise in PT IgG from 18-months to 21-35 days after vaccination with estimated difference [posterior median (95% CrI)] of 0.02 (-0.02, 0.07).*

*__4.__ For descriptive summaries of solicited local reactions and solicited systemic reactions see @sec-reactogenicity and for safety reporting summaries see @sec-safety.*

[^1]: Formerly known as Telethon Kids Institute

\clearpage
