
# Introduction

## Purpose

This report summarises the data and results of the analyses for main outcomes of the OPTIMUM
trial. 
The report includes results for:

- participant disposition
- participant baseline characteristics
- skin prick tests (SPTs)
- IgE-mediated food allergy
- eczema
- safety
- reactogenicity
- parental acceptability
- immunogenicity

For full details of the trial processes, objectives, and outcomes refer to the protocol [@chacon2020OPTIMUMStudyProtocol] and statistical analysis plan [@totterdell2022StatisticalAnalysisPlan].

## Interventions

Participants were randomised 1:1 to receive either:

- Combined Diphtheria (D)-Tetanus (T)-acellular Pertussis (aP), Hepatitis B (HepB), Inactivated Poliovirus (IPV) and *Haemophilus influenzae* type b (Hib) vaccine (DTaP-HepB-IPV-Hib) administered at approximately 2 months (referred to as 3-aP + aP or aP for short), together with the standard schedule of vaccines, or
- Combined Diphtheria (D)-Tetanus (T)-whole-cell Pertussis (wP), Hepatitis B (HepB) and *Haemophilus influenzae* type b (Hib) vaccine (DTwP-HepB-Hib) in place of DTaP-HepB-IPV-Hib at approximately 2 months (referred to as 1-wP/2-aP + aP or wP for short), together with the standard schedule of vaccines.

## Trial design

Originally, a maximum sample size of 3,000 participants was planned. Under the adaptive design, as outlined in the protocol [@chacon2020OPTIMUMStudyProtocol] and statistical analysis plan [@totterdell2022StatisticalAnalysisPlan], we estimated the trial had 85% power to detect a reduction in IgE-mediated food allergy from 10% to 7% with type I error of 5%. If $\delta$ denotes the difference in probability of IgE-mediated food allergy under each intervention, then trial success required that $\delta$ was very likely to be less than zero, specifically that $\Pr(\delta < 0) > 0.95$.

The maximum sample size was subsequently revised down to 2,000 participants due to feasibility constraints. The trial was stopped early due to logistical issues with 972 participants randomised.

## Trial outcomes

A summary of trial outcomes is provided below.

### Primary outcome (1) {#sec-primary-outcome}

IgE-mediated food allergy with evidence of food sensitisation on SPT by 12 months old and confirmed (where necessary) by medically supervised oral food challenge(s) (OFC). For the purpose of this trial, if either of the following conditions are met, the study participant was considered to have reached the primary endpoint:

1.  Unequivocal evidence of IgE-mediated food allergy, defined as:
    i.  A positive OFC with evidence of sensitisation on SPT to the food of interest *OR*
    ii. History of clinician-confirmed food anaphylaxis, with symptoms affecting at least two of the following: skin, gastrointestinal tract, respiratory tract, cardiovascular system; *AND* evidence of sensitisation on SPT to the food of interest.
2.  Highly probable IgE-mediated food allergy defined as a history of food allergic reaction (consistent with PRACTALL criteria [@sampson2012StandardizingDoubleblindPlacebocontrolled]), *AND* evidence of sensitisation on SPT to the food of interest.

We will report on the number and proportion who satisfy this composite definition, and the number and proportion satisfying each of the three sub-components as per a hierarchy in order of 1.i, 1.ii, 2.

### Secondary outcomes (2) {#sec-secondary-outcomes}

#### Clinical

a.  A history of parent-reported clinician-diagnosed new onset eczema by **6 months** *AND* a positive SPT to any allergen by approximately 12 months old.
b.  A history of parent-reported clinician-diagnosed new onset eczema by **12 months** *AND* a positive SPT to any allergen by approximately 12 months old.
c.  An SPT more than 1mm greater than (**\>1mm**) the negative control to at least one allergen by approximately 12 months of age
d.  An SPT at least 3mm greater than (**≥3mm** than the negative control to at least one allergen by approximately 12 months of age

#### Reactogenicity

Solicited and unsolicited adverse events following immunisation were collected on diary cards in the 7 days after administration of pertussis-containing vaccines for the first 300 participants at PCH. Solicited local adverse events included injection site pain, erythema, induration and swelling; the solicited systemic adverse events recorded were fever ≥38°C (axillary), drowsiness, irritability, anorexia, vomiting, diarrhoea and restlessness.

The definition and intensity grading for fever, diarrhoea and local reactions (except for immunisation site pain) followed the Brighton Collaboration guidelines [@michaelmarcy2004FeverAdverseEvent; @gidudu2011DiarrheaCaseDefinition; @gidudu2008LocalReactionInjection; @kohl2007SwellingInjectionSite; @kohl2007IndurationInjectionSite]. For other solicited adverse events, intensity grading scales based on impact on daily activities were used (grade 0 or absent; grade 1 if easily tolerated; grade 2, sufficiently discomforting to interfere with normal everyday activities and grade 3, if prevents normal everyday activities or requires significant medical intervention).

Parental acceptability was also measured using a 5-point Likert scale for whether the parent would be willing to have another child have the combination of vaccinations at the given age.

#### Immunological outcomes

##### IgE

Total, TT and food allergen-specific IgE were measured in plasma at the age of 6, 7 and 19 months (stage 1 only), using ImmunoCAP total and specific IgE assays (Thermo Fisher Scientific/Phadia, Uppsala, Sweden).

Interest was in the geometric mean concentrations and geometric mean fold-rise following the third pertussis containing vaccine (i.e. from 6 to 7 months of age) and the proportion of IgE concentrations above the limit of detection (≥0.01 kU/L) on each occasion.

##### IgG

Vaccine antigen-specific IgG concentrations were measured immediately before and 21–35 days after the 6-month (stage 1 only) and 18-month vaccine doses. These antibody levels were measured using a multiplex fluorescent bead assay. For stage 1, sera were tested for IgG against *B. pertussis* antigens (PT, filamentous haemagglutinin (FHA), pertactin (PRN), fimbriae agglutinogens 2–3 (FIM2/3)), TT, capsular polysaccharide of Hib (Hib-PRP), diptheria toxoid (DT), hepatitis B surface antigen (HBsAg), and each of the 13-valent pneumococcal vaccine serotypes (PnPs). For stage 2, sera were only tested for a subset of antigens and the 18 and/or 19-month ages.

Interest was in the geometric mean concentrations, seropositivity (13vPCV serotype-specific IgG ≥0.35 μg/mL, TT and DT ≥0.1 IU/mL, FHA, FIM2/3, PRN, and PT ≥5 IU/mL, HBsAg ≥10 mIU/mL, Hib-PRP ≥0.15 μg/mL at 6 and 7 months old and ≥1 μg/mL at 18 and 19 months old), and geometric mean fold-rise following the 18-month vaccination and the proportion of infants with at least a 4-fold rise, particularly for PT.

### Additional outcome details

The protocol defined allergen panel for skin prick tests included cow’s milk, hen’s egg, peanut, cashew, house dust mite (*Dermatophagoides pteronyssinus*), cat, rye grass (*Lolium perenne*), a positive control (10 mg/mL histamine) and negative control (saline). In addition to these, further allergens could also be tested at parental request or at discretion of the site principal investigator (PI). When the outcomes say "at least one allergen" [i.e. for eczema for positive SPT] it was meant any allergen, including any additional allergens tested beyond the standard panel.

For SPT's, the specification of "by approximately 12-months old" was taken to mean "up to 18-months old". Under the original protocol, SPTs were scheduled to occur at 18-months of age, but following an early revision, scheduled SPTs were revised to occur at 12-months of age. Unscheduled SPTs could still occur up to 18 months of age.

For both IgE-mediated food allergy and eczema, sensitisation on (positive) SPT was defined to be a result more than 1mm greater than negative control by 18 months of age. For IgE-mediated food allergy, the positive SPT needed to match the specific food allergen. 

For eczema, the age requirement (by 6 or 12 months of age) was determined by the "age at which allergy first occurred" (`outageval`). To be considered "new-onset" eczema, this age at which allergy first occurred needed to be after the infants enrolment date. Infants with clinician-diagnosed eczema first occurring prior to enrolment were to be excluded as cases which were not "new-onset eczema".

## Analyses

Unless otherwise stated, all summaries and analyses group participants according to their assigned treatment group and use all available data irrespective of protocol deviations or other intercurrent events (ITT).

Statistical analyses were conducted using Bayesian inference on assumed probabilistic models. The probabilistic model defines what observations are possible and how observations are related. Bayesian inference allocates and reallocates (in light of observed data) credibility across the possibilities. The result is a probability distribution over quantities of interest summarising uncertainty in their values where more plausible values have higher probability. These distributions are generally summarised by their median, 95% equal-tailed credible intervals (bounds for the central portion of the distribution which values contribute 95% of the probability), and probability of direction of effect.

### Primary outcome {#sec-primary-analysis}

The primary analysis was to assume independent Binomial models for occurrence of IgE-mediated food allergy under each treatment group with uniform priors on the outcome probabilities. 

::: {.callout-note}

## Primary model

Let $\theta_{\text{wP}}$ and $\theta_{\text{aP}}$ denote the probability of the outcome amongst infants who are assigned to the respective strategy and $\delta = \theta_{\text{wP}} - \theta_{\text{aP}}$ the difference in probablity. If $n_{\text{wP}}$ and $n_{\text{aP}}$ infants were assigned to each respective strategy, with $y_{\text{wP}}$ and $y_{\text{aP}}$ events observed, then from our assumed model we estimate that $\theta_j \sim \text{Beta}(1 + y_j, 1 + n_j - y_j)$ quantifies our uncertainty and $\delta$ the difference between these.

:::

A secondary analysis was to assume a logistic regression model for occurrence of IgE-mediated food allergy adjusting for baseline factors: site, sex, breastfeeding status, birth order, parental income, mode of delivery, and family history of atopic disease.

### Secondary outcomes (2) - clinical

Analyses of secondary clinical outcomes are analogous to those for the primary outcome, both the primary and secondary models.

### Geometric mean concentrations

Both the IgE and IgG concentrations were analysed assuming multivariate normal models on the log~10~ transformed concentrations with an unstructured covariance matrix shared across all participants. Analyses were undertaken on the scale of the lab-reported units.

The geometric mean ratio (GMR) of wP relative to aP on each occasion was calculated for each allergen and antigen type. Additionally, geometric mean fold rise ratios (GMFRR) of wP relative to aP are calculated for relevant sequential occasions.

In the analysis of allergen-specific IgE concentrations, some values were reported as 0.00 kU/L (6-month and 7-month) or 0.000 kU/L (19-month). These values were treated as left-censored at 0.005 kU/L and 0.0005 kU/L respectively to satisfy the model condition that concentrations were above 0 for all participants.

All models adjusted for the same covariates as specified for the primary outcome. Effects were allowed to vary by study visit.

::: {.callout-note}

## Concentration model

For infants $i=1,\ldots,n$ measured on occasions $j=1,\ldots,J$ (at most $J = 4$: 6-month, 7-month, 18-month, and 19-month), with model covariates $p = 1,\ldots,P$, the pre-specified model for concentration $Y_i$ was

$$
\begin{aligned}
\log_{10}(Y_i) &\sim \text{Normal}_J(\mu_i, \Sigma) \\
\mu_{ij} &= \alpha_j + x_{ij}^\mathsf{T}\beta_j \\
\Sigma &= \text{diag}(\sigma)\Omega\text{diag}(\sigma) \\
\alpha_j &\sim \text{Normal}(0, 10^2), \quad j=1,\ldots,J \\
\beta_{jp} &\sim \text{Normal}(0, 10^2), \quad j=1,\ldots,J,\ p=1,\ldots,P \\
\Omega &\sim \text{LKJ}(1) \\
\sigma_j &\sim \text{Cauchy}^+(0, 10), \quad j=1,\ldots,J.
\end{aligned}
$$

:::

### Binary outcomes (quantitation, seropositivity, four-fold rise)

For binary outcomes, logistic regression models were assumed. If the outcome consists of multiple responses per participant then a participant-specific random intercept was included in the model. All models adjusted for the same covariates as specified for the primary outcome. Effects were allowed to vary by study visit.

::: {.callout-note}

## Binary outcome model

Denote by $Y_{ij}$ the binary outcome for participant $i$ on occasion $j$, then the model was
$$
\begin{aligned}
  Y_{ij} &\sim \text{Bernoulli}(\pi_{ij}) \\
  \pi_{ij} &= \text{logit}^{-1}(\eta_{ij}) \\
  \eta_{ij} &= \alpha + \omega_j + z_i\theta_j + \sum_{p=1}^Px_{ip}\beta_{jp} + \gamma_i \\
  \gamma|\tau^2 &\sim \text{Normal}(0, \tau^2) \\
  \omega_1 &= 0 \\
  \alpha, \omega_{2:J}, \theta, \beta &\sim \text{Student-t}(4, 0, 1.75^2) \\
  \tau &\sim \text{Exponential}(1)
\end{aligned}
$$

:::

### Quantity Definitions

**Geometric mean concentration**: For concentrations $x_1,\ldots,x_n$, the geometric mean concentration (GMC) is just the geometric mean of the concentrations, i.e.

$$
\text{GMC} = \exp\left(n^{-1}\sum_{i=1}^n \ln x_i\right).
$$

Under a log-normal model, where $\ln X \sim \text{Normal}(\mu, \sigma^2)$, the geometric mean of $X$ is just $\exp(\mu)$.

**Geometric standard deviation**: The geometric standard deviation (GSD) if a collection of values $x_1,\ldots,x_n$ is

$$
\text{GSD} = \exp\left(\sqrt{n^{-1}\sum_{i=1}^n \left(\ln\frac{x_i}{\text{GM}}\right)^2}\right)
$$

where $\text{GM}$ is the geometric mean of $x_1,\ldots,x_n$.

Under a log-normal model, where $\ln X \sim \text{Normal}(\mu, \sigma^2)$, the geometric standard deviation of $X$ is just $\exp(\sigma)$.

**Geometric mean ratio**: the geometric mean ratio (GMR) between two groups is the ratio of the geometric mean concentration in each group. For example, if $\text{GMC}_{\text{wP}}$ is the GMC under the wP schedule, and $\text{GMC}_{\text{aP}}$ under the aP schedule, then the GMR of wP compared to aP is

$$
\text{GMR} = \frac{\text{GMC}_{\text{wP}}}{\text{GMC}_{\text{aP}}}.
$$

**Geometric mean fold-rise**: the fold-rise is the ratio of a subject's pre and post-vaccination immunogenicity value. That is, if $x_{i1}$ was their pre concentration and $x_{i2}$ their post concentration, then their fold-rise was $x_{i2}/x_{i1}$. The geometric mean fold-rise (GMFR) is the geometric mean of a collection of fold-rises which also equals the ratio of the pre and post geometric mean concentrations, that is

$$
\text{GMFR} = \exp\left(n^{-1}\sum_{i=1}^n \ln \frac{x_{i2}}{x_{i1}}\right)=\frac{\text{GMC}_2}{\text{GMC}_1}.
$$

**Geometric mean fold-rise ratio**: the geometric mean fold-rise ratio (GMFRR) between two groups is the ratio of the geometric mean fold-rise in each group which also equals the ratio of the pre and post geometric mean ratios between the two groups. For example, if $\text{GMFR}_{\text{wP}}$ is the GMFR under the wP schedule, and $\text{GMFR}_{\text{aP}}$ under the aP schedule, then the GMFRR of wP compared to aP is

$$
\text{GMFRR} = \frac{\text{GMFR}_{\text{wP}}}{\text{GMFR}_{\text{aP}}} = \frac{\text{GMR}_2}{\text{GMR}_1}.
$$

### Software

Summaries and analyses were performed in R (4.5.3) [@R]. Where necessary, Bayesian inference was performed using Stan (2.38.0) [@Stan] via cmdstanr (0.9.0) [@cmdstanr].

\clearpage
