# Additional Information

## Primary outcome listing {#sec-primary-outcome-listing}
  
```{r}
#| label: tbl-listing-ofc-matched-foods
#| tbl-cap: |
#|    Listing of infants with OFC outcome by 18 months of age and corresponding SPT positive allergens.
#| tbl-pos: "H"
dat_po_ofc |>
  filter(po_ofc) |>
  select(record_id, trt, po_ofc_foods, po_ofc_match) |>
  gt() |>
  cols_label(
    trt ~ "Treatment",
    po_ofc_foods ~ "OFC positive foods",
    po_ofc_match ~ "Foods with positive SPT"
  ) |>
  tab_options(table.font.size = px(9), table.width = pct(75)) |>
  tab_footnote(
    footnote = "These were from free-text fields on the outcome report. Responses are reported as documented.",
    locations = cells_column_labels(columns = po_ofc_foods),
    placement = "right"
  )
```

```{r}
#| label: tbl-listing-ana-matched-foods
#| tbl-cap: Listing of infants with food anaphylaxis outcome by 18 months of age and corresponding SPT positive allergens.
#| tbl-pos: "H"
dat_po_ana |>
  filter(po_ana) |>
  select(record_id, trt, po_ana_foods, po_ana_match) |>
  gt() |>
  cols_label(
    trt ~ "Treatment",
    po_ana_foods ~ "Anaphylactic triggers",
    po_ana_match ~ "Foods with positive SPT"
  ) |>
  tab_options(table.font.size = px(9), table.width = pct(75)) |>
  tab_footnote(
    footnote = "These were from free-text fields on the outcome report. Responses are reported as documented.",
    locations = cells_column_labels(columns = po_ana_foods),
    placement = "right"
  )
```

```{r}
#| label: tbl-listing-ige-matched-foods
#| tbl-cap: |
#|    Listing of infants with highly probable IgE-mediated food allergy outcome by 18 months of age and corresponding
#|    SPT positive allergens.
#| tbl-pos: "H"
dat_po_ige |>
  filter(po_ige) |>
  select(record_id, trt, po_ige_foods, po_ige_match) |>
  gt() |>
  cols_label(
    trt ~ "Treatment",
    po_ige_foods ~ "Suspected food allergen",
    po_ige_match ~ "Foods with positive SPT"
  ) |>
  tab_options(table.font.size = px(9), table.width = pct(75)) |>
  tab_footnote(
    footnote = "These were from free-text fields on the outcome report. Responses are reported as documented.",
    locations = cells_column_labels(columns = po_ige_foods),
    placement = "right"
  ) |>
  tab_footnote(
    footnote = paste0(
      "In some instances, separate SPTs for egg yolk and egg white were ",
      "reported rather than one SPT for whole egg."
    ),
    locations = cells_column_labels(columns = po_ige_match),
    placement = "right"
  )
```

```{=latex}
\clearpage
```

## Secondary outcome listings

```{r}
#| label: tbl-listing-eczema
#| tbl-cap: Listing of infants with eczema diagnosis and positive SPT to any allergen.
#| tbl-pos: "H"
dat_ecz_spt |>
  filter(!out_ecz_preexisting, ecz, any_pos_spt) |>
  mutate(
    age_diag_months = interval(birthdat, outdiagdat) %/% months(1) + 1,
  ) |>
  select(record_id, trt, outageval_months2) |>
  gt() |>
  fmt_number(decimals = 0) |>
  cols_label(
    trt ~ "Treatment",
    outageval_months2 ~ "Age at first reaction (months)"
  ) |>
  tab_options(
    table.font.size = px(9),
    table.width = pct(60),
    latex.use_longtable = TRUE
  )
```

```{=latex}
\clearpage
```

## Additional IgG concentration summaries


```{r}
#| label: fig-igg-ecdf-dtap
#| fig-cap: |
#|    Complementary empirical cumulative distribution of serotype-specific IgG concentrations by age and assigned schedule.
#|    Vertical line indicates seropositivity reference value.
#| fig-width: 7
#| fig-height: 6
lab_fun <- function(x) {
  ifelse(x < 1, sprintf("%.2f", x), sprintf("%.0f", x))
}
p_fig <- dat_igg |>
  filter(type != "PnPs") |>
  ggplot(aes(concentration, colour = trt)) +
  facet_grid(antigen ~ visage) +
  stat_ecdf(aes(y = after_stat(1 - ecdf)), geom = "step") +
  geom_vline(aes(xintercept = ref), linetype = 2) +
  scale_x_log10(
    breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
    labels = lab_fun
  ) +
  labs(x = "IgG concentration", y = "Complementary empirical cumulative distribution", colour = "") +
  paletteer::scale_colour_paletteer_d("ggsci::alternating_igv") +
  theme(legend.position = "top")
p_fig
```

```{r}
#| label: fig-igg-ecdf-pneumo
#| fig-cap: |
#|    Complementary empirical cumulative distribution of serotype-specific IgG concentrations by age and assigned schedule.
#|    Vertical line indicates 0.35 μg/mL.
#| fig-width: 7
#| fig-height: 8
lab_fun <- function(x) {
  ifelse(x < 1, sprintf("%.2f", x), sprintf("%.0f", x))
}
p_fig <- dat_igg |>
  filter(type == "PnPs") |>
  ggplot(aes(concentration, colour = trt)) +
  facet_grid(antigen ~ visage) +
  stat_ecdf(aes(y = after_stat(1 - ecdf)), geom = "step") +
  geom_vline(xintercept = 0.35, linetype = 2) +
  scale_x_log10(
    breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
    labels = lab_fun
  ) +
  labs(x = "IgG concentration", y = "Complementary empirical cumulative distribution", colour = "") +
  paletteer::scale_colour_paletteer_d("ggsci::alternating_igv") +
  theme(legend.position = "top")
p_fig
```

```{r}
#| label: igg-marginal-plot-functions
igg_progress_plot <- function(dat) {
  dat |>
    ggplot(aes(visage, concentration)) +
    facet_grid(antigen ~ trt, scales = "free_y") +
    geom_point(alpha = 0.5) +
    geom_path(aes(group = subjid), alpha = 0.5) +
    stat_summary(geom = "point", fun = mean, colour = "red", shape = 22) +
    scale_y_log10()
}

igg_marginal_plots_1 <- function(dat) {
  p <- dat |>
    select(subjid, antigen, visage, trt, concentration) |>
    to_factor() |>
    arrange(antigen) |>
    pivot_wider(names_from = visage, values_from = concentration) |>
    filter(!(is.na(`6-month`) | is.na(`7-month`))) |>
    ggplot(aes(`6-month`, `7-month`)) +
    geom_point(shape = 21, size = 1, alpha = 0.7, fill = "white") +
    geom_abline(intercept = 0, slope = 1, linetype = 2, linewidth = 0.2) +
    geom_xsidehistogram(bins = 20) +
    geom_ysidehistogram(bins = 20) +
    scale_x_log10(
      "6-month IgG (log scale)",
      breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
      labels = comma
    ) +
    scale_y_log10(
      "7-month IgG (log scale)",
      breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
      labels = comma
    ) +
    scale_xsidey_continuous(n.breaks = 2, position = "left") +
    scale_ysidex_continuous(n.breaks = 2) +
    # coord_fixed() +
    facet_grid(antigen ~ trt, space = "free", switch = "y") +
    ggside(scales = "free", y.pos = "right") +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1),
      ggside.panel.scale.y = 0.3,
      ggside.panel.scale.x = 0.3,
      ggside.axis.text = element_blank(),
      ggside.axis.ticks = element_blank(),
      strip.placement = "outside"
    )
  return(p)
}

igg_marginal_plots_2 <- function(dat) {
  p <- dat |>
    select(subjectid, antigen, age, treatment, concentration) |>
    to_factor() |>
    arrange(antigen) |>
    pivot_wider(names_from = age, values_from = concentration) |>
    filter(!(is.na(`18-month`) | is.na(`19-month`))) |>
    ggplot(aes(`18-month`, `19-month`)) +
    geom_point(shape = 21, size = 1, alpha = 0.7, fill = "white") +
    geom_abline(intercept = 0, slope = 1, linetype = 2, linewidth = 0.2) +
    geom_xsidehistogram(bins = 20) +
    geom_ysidehistogram(bins = 20) +
    scale_x_log10(
      "18-month IgG (log10 scale)",
      breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
      labels = comma
    ) +
    scale_y_log10(
      "19-month IgG (log10 scale)",
      breaks = c(0, 0.01, 0.1, 1, 10, 100, 1000),
      labels = comma
    ) +
    scale_xsidey_continuous(n.breaks = 2, position = "left") +
    scale_ysidex_continuous(n.breaks = 2) +
    # coord_fixed() +
    facet_grid(antigen ~ treatment, space = "free", switch = "y") +
    ggside(scales = "free", y.pos = "right") +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1),
      ggside.panel.scale.y = 0.3,
      ggside.panel.scale.x = 0.3,
      ggside.axis.text = element_blank(),
      ggside.axis.ticks = element_blank(),
      strip.placement = "outside"
    )
  return(p)
}
```

```{=latex}
\clearpage
\phantomsection
```

# References {.unnumbered}

::: {#refs}
:::
