```{r}
#| label: packages-and-setup
#| code-summary: Setup session
suppressPackageStartupMessages({
  # Data
  library(here)
  library(qs)
  library(dplyr)
  library(tidyr)
  library(forcats)
  library(lubridate)
  library(stringr)
  library(labelled)
  library(REDCapTidieR)

  # Figures
  library(ggplot2)

  # Tables
  library(reactable)
  library(reactablefmtr)
  library(gt)
  library(gtsummary)
})

readRenviron(here(".env"))

source(here("R", "util.R"))
source(here("R", "data", "process-combined-data.R"))

theme_set(
  theme_bw(base_size = 10) +
    theme(panel.grid.minor = element_blank())
)

options(
  reactable.theme = journal(
    font_size = 10,
    header_font_size = 11,
    cell_padding = 4
  )
)
```

```{r}
#| label: data
#| code-summary: Load raw data
st2_file <- file.path(
  Sys.getenv("RDS_PATH"),
  config::get("raw_data_stage2_path"),
  config::get("raw_data_stage2_file")
)
com_file <- file.path(Sys.getenv("RDS_PATH"), config::get("combined_data_file"))

dat_raw <- qread(com_file)
dat_base <- get_baseline_data(dat_raw, TRUE)
dat_ran <- select(dat_base, record_id, trt, randdat)
```
